# App configurations
app:
  name: "Keycloak Api Gateway"
  language: en-GB
  static: ./httpdocs
  session-age: 60
  #0 to 4
  strong-pass-level: 0
#
jwt:
  secret: "a.random.public.key"
  issuer: "io"
  audience: ["*"]
  age: 24h
  subject: "Keycloak Api Backend"
#
# Server configurations
server:
  host: "0.0.0.0"
  port:  "8010"
  https: false
  cert:  cert.pem
  key:   key.pem
  name:  "EVO"
  strict-routing: false
  case-sensitive: false
  max-upload-size: 1M
  request-id: false
  debug: true
  recover: false
#
#Log to file
log:
  writefile: true
  size: 5
  age: 7
  level: debug
  path: ./logs
#
#Cross Origin Resource Sharing
cors:
  enabled: true
  allowed-origins: ["*"]
  allowed-methods: ["GET","POST","HEAD","OPTION","PUT","PATCH","DELETE"]
  allowed-credentials: true
  allowed-headers: ["*"]
  max-age: 0
#

keycloak:
  server: 
  realm: 
  client: 
  username: admin@keycloak.com
  password: 
  client_secret: 
#
